spring:
	application:
		name: stock-fin-service
		
server:
	port: 8088		

eureka:
	client:
		registerWithEureka: true
		fetchRegistry: true
		serviceUrl:
			defaultZone: http://localhost:8087/eureka/
	instance:
		hostname: localhost